---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: update & upgrade packages (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "ubuntu"
      
    - name: update & upgrade packages (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
