- name: update & upgrade packages (Ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: update & upgrade packages (CentOS)
  dnf:
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "CentOS"
